name: houdina
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  email_validator: ^2.1.17

  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  cloud_firestore: ^4.13.2
  firebase_app_check: ^0.2.1+8
  file_picker: ^6.1.1
  firebase_storage: ^11.5.2

  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^1.0.0
  http: ^0.13.3
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - resources/Background.jpg
    - resources/Logo.png
    - resources/default.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/Logo.png"
